"""VLMux Action Protocol (VAP) models and serialization helpers."""

from vlmux.protocol.actions import (
    Action,
    BrowserBackAction,
    BrowserForwardAction,
    BrowserNavigateAction,
    BrowserReloadAction,
    ClickAction,
    CloseWindowAction,
    DoubleClickAction,
    DragAction,
    FailAction,
    FinishAction,
    FocusWindowAction,
    HotkeyAction,
    KeyAction,
    MoveCursorAction,
    OpenAppAction,
    PasteAction,
    RightClickAction,
    ScreenshotAction,
    ScrollAction,
    TypeAction,
    WaitAction,
    action_json_schema,
    dump_action_json,
    parse_action_json,
)

__all__ = [
    "Action",
    "BrowserBackAction",
    "BrowserForwardAction",
    "BrowserNavigateAction",
    "BrowserReloadAction",
    "ClickAction",
    "CloseWindowAction",
    "DoubleClickAction",
    "DragAction",
    "FailAction",
    "FinishAction",
    "FocusWindowAction",
    "HotkeyAction",
    "KeyAction",
    "MoveCursorAction",
    "OpenAppAction",
    "PasteAction",
    "RightClickAction",
    "ScreenshotAction",
    "ScrollAction",
    "TypeAction",
    "WaitAction",
    "action_json_schema",
    "dump_action_json",
    "parse_action_json",
]
